---
- hosts: all
  connection: local
  become: sudo

  roles:
    - common
    - fail2ban
    - ferm
    - php
    - memcached
    - mariadb
    - nginx
    - wp-cli
    - { role: letsencrypt, tags: [letsencrypt], when: letsencrypt_enabled }
    - { role: sites, enviro: php, tags: [ 'sites' ] }
